{
 "title": "07",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes {job=\"node\"}"
    },
    {
     "expr": "node_memory_MemTotal_bytes {job=\"node\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[5m])) without(cpu)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"node\", device=\"sda\"}[5m])",
     "legendFormat": "Count output operations"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"node\", device=\"sda\"}[5m])",
     "legendFormat": "Count input operations"
    }
   ]
  }
 ]
}